const CLASSES = {
  SECTION_SLIDER: ".section__slider",
  SECTION_PAGINATION: ".section__pagination",
  BUTTON_LEFT: ".button_left",
  BUTTON_RIGHT: ".button_right",
  PAGINATION_CARDS: ".pagination__cards",
  CARD_IMG: ".card__img",
  CARD__BUTTON: ".card__button",
  CARD: ".card",
  CARDS: ".cards",
  PAGINATION_BUTTONS: ".pagination__buttons",
  BUTTON: ".button",
  SLIDER: ".slider",
  CARDS_CONTAINER: ".cards__container",
};
const CONSTANTS = {
  BUTTON: "button",
  DIV: "div",
  UL: "ul",
  LI: "li",
  IMG: "img",
  BUTTON_LEFT: "button_left",
  BUTTON_RIGHT: "button_right",
  ARROW_LEFT: "<",
  ARROW_RIGHT: ">",
  CLICK: "click",
  ANIMATION_LEFT: "animation_left",
  ANIMATION_RIGHT: "animation_right",
};
export { CLASSES, CONSTANTS };
